### ISSUE TITLE
Add repo informations like label: nostr bounty & add link to bountsr.org

### ISSUE THREAD

**Issue by gourcetools** [coinkite/bountsr.org.pub#13]
I think it would be great.

**Comment by nvk** [comment]
Not sure what you mean

**Comment by gourcetools** [comment]
![image](https://user-images.githubusercontent.com/120996278/222918342-598db06f-f7be-439b-8a47-7536a0bb2558.png)
Fill this part.

**Comment by nvk** [comment]
done.
